### ISSUE TITLE
请教如何转换ncnn模型~~

### ISSUE THREAD

**Issue by ChungTak** [zjd1988/seetaface6_onnx_model#2]
你好·~请问模型有没有办法在ncnn或者mnn其他推理框架中使用？
我试了一下转换都是出错 。
还有face_detector.onnx模型输入和输出为何都是 -1 的？

**Comment by zjd1988** [comment]
@ChungTak  按道理是可以转换的，你可以通过onnx-simply 把模型输入和输出固定下来，然后再用mnn或者ncnn转换，或者你把报错信息发下

**Comment by ChungTak** [comment]
感谢你的回复，·输入和输出应该固定多少，是不是随便填一个值都可以呢？·我不太懂这个~
我查了一下onnx-simplifier 有输入参数--input-shape但没找到输出参数
运行 python3 -m onnxsim models/face_detector.onnx models/face_detector_opt.onnx --input-shape  1,3,640,640
再使用 onnx2ncnn  face_detector_opt.onnx  转ncnn没有报错了~~

netro查看face_detector_opt.onnx 感觉有点怪detection_dimension_float_115 独立了出来，和之前的很大差别，不知道有没有问题。
![1642756122(1)](https://user-images.githubusercontent.com/778353/150499110-e7949795-5271-442c-b053-22dbd07c6050.png)

**Comment by ChungTak** [comment]
刚试了一下 rknn-toolkit框架转换报这个错,是不是由于输出没固定引起？要怎样固定输出呢？
```
E load_onnx: Traceback (most recent call last):
E load_onnx:   File "rknn/api/rknn_base.py", line 1126, in rknn.api.rknn_base.RKNNBase.load_onnx
E load_onnx:   File "rknn/api/rknn_base.py", line 584, in rknn.api.rknn_base.RKNNBase._create_ir_and_inputs_meta
E load_onnx:   File "rknn/api/ir_graph.py", line 39, in rknn.api.ir_graph.IRGraph.__init__
E load_onnx:   File "rknn/api/ir_graph.py", line 180, in rknn.api.ir_graph.IRGraph.rebuild
E load_onnx:   File "rknn/api/ir_graph.py", line 140, in rknn.api.ir_graph.IRGraph._clean_model
E load_onnx:   File "rknn/api/ir_graph.py", line 56, in rknn.api.ir_graph.IRGraph.infer_shapes
E load_onnx:   File "/root/miniconda3/envs/rknn2-1.2.0/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
E load_onnx:     inferred_model_str = C.infer_shapes(model_str, check_type)
E load_onnx: RuntimeError: Inferred shape and existing shape differ in dimension 0: (1) vs (-1)

```

**Comment by zjd1988** [comment]
@ChungTak   或者你把你的需求告诉我，我转好后，把转换的脚本发你

**Comment by ChungTak** [comment]
@zjd1988  大神~太棒~~
我现在想把你的onnx模型转成[rknn模型](https://github.com/rockchip-linux/rknn-toolkit2)
请问你的微信号是多少?

**Comment by zjd1988** [comment]
@ChungTak 我的qq是 942002795
