### ISSUE TITLE
请问有没有人脸特征提取的相关复现，应该是在FaceRecognizer模块

### ISSUE THREAD

**Issue by w-Bro** [zjd1988/seetaface6_onnx_model#3]

**Comment by zjd1988** [comment]
模型已经有做转换，但是前后处理的逻辑还没转成py代码
@[w-Bro](https://github.com/w-Bro) 你可以调试parse_csta.py脚本，执行完parse_csta_model_file函数后，可以查看模型的前处理和后处理的内容
![企业微信截图_16449250813396](https://user-images.githubusercontent.com/7134030/154054840-cd6970d3-9a04-4fa5-a50d-49197e793a75.png)
从截图看，前处理基本不需要做（只要你的输入的分辨率是248x248）
后处理的话，需要做开方和归一化操作
![企业微信截图_16449251917592](https://user-images.githubusercontent.com/7134030/154055082-f5be2fee-4411-4afb-a845-10bff68b5d29.png)


下面的是face_recognizer_light.onnx模型的前后处理和推理代码，你可以对比的看下
下图是需要做前后处理
![企业微信截图_16449254843452](https://user-images.githubusercontent.com/7134030/154055762-8060f360-b4bd-49fb-a21c-0d5f0aadadec.png)


对应的推理代码如下：
![企业微信截图_1644925544228](https://user-images.githubusercontent.com/7134030/154055927-fb8ab7c9-b6c7-421b-af67-82860397eaf0.png)

**Comment by w-Bro** [comment]
@zjd1988 感谢！已经计算出特征值，但是经过相似度计算，结果都是0.99以上，好像并不准确。我本地没有C++环境，使用的是[seetaFace6Python](https://github.com/tensorflower/seetaFace6Python)做对比，这个项目因为在多线程的情况下会崩溃，所以没有使用他，只能当作测试跑一下。

- seetaFace6Python的代码
```python
image3 = cv2.imread("asserts/crop1.jpg")
feature3 = seetaFace.ExtractCroppedFace(image3)
# 将特征转numpy格式
feature3 = seetaFace.get_feature_numpy(feature3)

image4 = cv2.imread("asserts/crop2.jpg")
feature4 = seetaFace.ExtractCroppedFace(image4)
# 将特征转numpy格式
feature4 = seetaFace.get_feature_numpy(feature4)

similar2 = seetaFace.compare_feature_np(feature3,feature4)
# 相似度为0.77
print(similar2)

# compare_feature_np，代码如下
def compare_feature_np(self, feature1: np.array, feature2: np.array) -> float:
    """
    使用numpy 计算，比较人脸特征值相似度
   :param feature1: 人脸特征值1
    :param feature2: 人脸特征值2
    :return: 人脸相似度
    """
    dot = np.sum(np.multiply(feature1, feature2))
    norm = np.linalg.norm(feature1) * np.linalg.norm(feature2)
    dist = dot / norm
    return float(dist)
```

其中，ExtractCroppedFace对应动态库的话是这段C++代码
![image](https://user-images.githubusercontent.com/24600584/154188537-05d8b74c-60e1-415f-84a6-89e2cfa960de.png)

- 使用onnx的代码
```python
# -*- coding: utf-8 -*-
import cv2
import onnxruntime
import numpy as np

onnx_file_name = '../models/face_recognizer.onnx'
onnx_session = onnxruntime.InferenceSession(onnx_file_name)


def get_feature(image):
    """
    提取裁剪后的人脸特征
    :param image:
    :return:
    """
    # 预处理
    input_feed = {}
    resize_img = cv2.resize(image, (248, 248))
    input_data = (resize_img / 255.0).transpose((2, 0, 1))
    input_feed["_input_123"] = input_data.reshape((1, 3, 248, 248)).astype(np.float32)

    # 预测
    pred_result = onnx_session.run([], input_feed=input_feed)

    # 后处理
    pred_result = pred_result[0].flatten()
    # 开方
    pred_result = np.sqrt(pred_result)
    # 归一化
    norm = pred_result / np.linalg.norm(pred_result)

    return norm


if __name__ == "__main__":

    feature1 = get_feature(cv2.imread("../crop1.jpg"))
    print(feature1.shape)
    feature2 = get_feature(cv2.imread("../crop2.jpg"))

    # 计算相似度
    dot = np.sum(np.multiply(feature1, feature2))
    norm = np.linalg.norm(feature1) * np.linalg.norm(feature2)
    dist = dot / norm
    # 结果都是0.99
    print(dist)
```

**Comment by zjd1988** [comment]
@[w-Bro](https://github.com/w-Bro) 方便提供下使用crop 图片吗（压缩包），我本地测试下。

**Comment by w-Bro** [comment]
@zjd1988 是这两张，谢谢！
https://github.com/tensorflower/seetaFace6Python/blob/master/asserts/crop1.jpg
https://github.com/tensorflower/seetaFace6Python/blob/master/asserts/crop2.jpg

**Comment by zjd1988** [comment]
> @zjd1988 是这两张，谢谢！ https://github.com/tensorflower/seetaFace6Python/blob/master/asserts/crop1.jpg https://github.com/tensorflower/seetaFace6Python/blob/master/asserts/crop2.jpg

刚才看了下onnx的网络结构，转出来的模型已经把除255的操作放在了网络里面，在预处理不需要再除以255了，你再试下
![企业微信截图_16449818802572](https://user-images.githubusercontent.com/7134030/154190329-c5192202-daff-4615-85bb-0a766f1d2fe1.png)

**Comment by w-Bro** [comment]
> > @zjd1988 是这两张，谢谢！ https://github.com/tensorflower/seetaFace6Python/blob/master/asserts/crop1.jpg https://github.com/tensorflower/seetaFace6Python/blob/master/asserts/crop2.jpg
> 
> 刚才看了下onnx的网络结构，转出来的模型已经把除255的操作放在了网络里面，在预处理不需要再除以255了，你再试下 ![企业微信截图_16449818802572](https://user-images.githubusercontent.com/7134030/154190329-c5192202-daff-4615-85bb-0a766f1d2fe1.png)

结果还有点差异，确实是可以了！

**Comment by zjd1988** [comment]
@w-Bro  差异大吗，如果差异不大，那可能是算子计算精度和实现方式的差异引起的
我看了下提供的两个图片的分辨率是256x256，你可以从中心抠出来248x248的子图，不要resize再试试

我试了下你说的那两个图，使用crop方式，而不是resize的方法得到的相似度为0.66194934，



```python
# -*- coding: utf-8 -*-
import cv2
import onnxruntime
import numpy as np

def get_feature(onnx_session, img_path):
    input_feed = {}
    img = cv2.imread(img_path)
    crop_img = img[4:252, 4:252, :]
    input_data = crop_img.transpose((2, 0, 1))
    input_feed['_input_123'] = input_data.reshape((1, 3, 248, 248)).astype(np.float32)
    pred_result = onnx_session.run([], input_feed=input_feed)
    # print(pred_result[0].shape)
    # post process
    # 1 sqrt feature
    temp_result = np.sqrt(pred_result[0])
    # 2 normalization feature
    norm = temp_result / np.linalg.norm(temp_result, axis=1)
    return norm


if __name__ == "__main__":
    onnx_file_name = './models/face_recognizer.onnx'
    onnx_session = onnxruntime.InferenceSession(onnx_file_name)
    feature1 = get_feature(onnx_session, "./crop1.jpg")
    feature2 = get_feature(onnx_session, "./crop2.jpg")
    sim = np.sum(feature1 * feature2 )
    print(sim)
```

**Comment by w-Bro** [comment]
> @w-Bro 差异大吗，如果差异不大，那可能是算子计算精度和实现方式的差异引起的 我看了下提供的两个图片的分辨率是256x256，你可以从中心抠出来248x248的子图，不要resize再试试
> 
> 我试了下你说的那两个图，使用crop方式，而不是resize的方法得到的相似度为0.66194934，
> 
> ```python
> # -*- coding: utf-8 -*-
> import cv2
> import onnxruntime
> import numpy as np
> 
> def get_feature(onnx_session, img_path):
>     input_feed = {}
>     img = cv2.imread(img_path)
>     crop_img = img[4:252, 4:252, :]
>     input_data = crop_img.transpose((2, 0, 1))
>     input_feed['_input_123'] = input_data.reshape((1, 3, 248, 248)).astype(np.float32)
>     pred_result = onnx_session.run([], input_feed=input_feed)
>     # print(pred_result[0].shape)
>     # post process
>     # 1 sqrt feature
>     temp_result = np.sqrt(pred_result[0])
>     # 2 normalization feature
>     norm = temp_result / np.linalg.norm(temp_result, axis=1)
>     return norm
> 
> 
> if __name__ == "__main__":
>     onnx_file_name = './models/face_recognizer.onnx'
>     onnx_session = onnxruntime.InferenceSession(onnx_file_name)
>     feature1 = get_feature(onnx_session, "./crop1.jpg")
>     feature2 = get_feature(onnx_session, "./crop2.jpg")
>     sim = np.sum(feature1 * feature2 )
>     print(sim)
> ```

我算出来也是0.66，seetaFace6Python计算出来是0.77，两边计算相似度的方法是一样的。

**Comment by zjd1988** [comment]
@[w-Bro](https://github.com/w-Bro) 嗯嗯，这个可能需要调试下c++工程，然后确认下是哪一步导致的差异。

**Comment by zjd1988** [comment]
@w-Bro  我这边跑了下seetaFace6Python工程跑出来的相似度是0.72，不过依然不同，还是得定位下差异是什么引起的
![企业微信截图_1644993532106](https://user-images.githubusercontent.com/7134030/154209965-0e500d11-aef7-4188-86cc-ff4b237c0e89.png)

**Comment by zjd1988** [comment]
@w-Bro  你好，我调试了下，模型没问题，预处理少了bgr2rgb这一步
```python
# -*- coding: utf-8 -*-
import cv2
import onnxruntime
import numpy as np

def get_feature(onnx_session, img_path):
    input_feed = {}
    img = cv2.imread(img_path)
    crop_img = img[4:252, 4:252, :][...,::-1]
    input_data = crop_img.transpose((2, 0, 1))
    # resize_img = cv2.resize(img, (248, 248))
    # input_data = resize_img.transpose((2, 0, 1))
    input_feed['_input_123'] = input_data.reshape((1, 3, 248, 248)).astype(np.float32)
    pred_result = onnx_session.run([], input_feed=input_feed)
    # print(pred_result[0].shape)
    # post process
    # 1 sqrt feature
    temp_result = np.sqrt(pred_result[0])
    # 2 normalization feature
    norm = temp_result / np.linalg.norm(temp_result, axis=1)
    return norm


if __name__ == "__main__":
    onnx_file_name = './new_model_with_middle.onnx'
    onnx_session = onnxruntime.InferenceSession(onnx_file_name)
    feature1 = get_feature(onnx_session, "./crop1.jpg")
    feature2 = get_feature(onnx_session, "./crop2.jpg")
    sim = np.sum(feature1 * feature2 )
    print(sim)
```
python 计算相似度为 0.7222837
c++      计算相似度为 0.722284
你可以在你本地验证下。

**Comment by w-Bro** [comment]
> @w-Bro 你好，我调试了下，模型没问题，预处理少了bgr2rgb这一步
> 
> ```python
> # -*- coding: utf-8 -*-
> import cv2
> import onnxruntime
> import numpy as np
> 
> def get_feature(onnx_session, img_path):
>     input_feed = {}
>     img = cv2.imread(img_path)
>     crop_img = img[4:252, 4:252, :][...,::-1]
>     input_data = crop_img.transpose((2, 0, 1))
>     # resize_img = cv2.resize(img, (248, 248))
>     # input_data = resize_img.transpose((2, 0, 1))
>     input_feed['_input_123'] = input_data.reshape((1, 3, 248, 248)).astype(np.float32)
>     pred_result = onnx_session.run([], input_feed=input_feed)
>     # print(pred_result[0].shape)
>     # post process
>     # 1 sqrt feature
>     temp_result = np.sqrt(pred_result[0])
>     # 2 normalization feature
>     norm = temp_result / np.linalg.norm(temp_result, axis=1)
>     return norm
> 
> 
> if __name__ == "__main__":
>     onnx_file_name = './new_model_with_middle.onnx'
>     onnx_session = onnxruntime.InferenceSession(onnx_file_name)
>     feature1 = get_feature(onnx_session, "./crop1.jpg")
>     feature2 = get_feature(onnx_session, "./crop2.jpg")
>     sim = np.sum(feature1 * feature2 )
>     print(sim)
> ```
> 
> python 计算相似度为 0.7222837 c++ 计算相似度为 0.722284 你可以在你本地验证下。

确实是，谢谢！

**Comment by DiaosWang** [comment]
两位大佬牛逼，受益匪浅。
