### ISSUE TITLE
能帮我把pose_estimation.onnx转成ncnn模型吗？

### ISSUE THREAD

**Issue by j201111100523** [zjd1988/seetaface6_onnx_model#5]

**Comment by zjd1988** [comment]
@j201111100523  你好，下载ncnn的仓库，按照编译步骤生成转换工具基本没什么坑，很顺利，你自己可以尝试下。

**Comment by j201111100523** [comment]
作者你好，通过你提供的脚本把onnx模型固定后，通过onnx2ncnn工具转换成了ncnn模型，但是结果如图：
![image](https://user-images.githubusercontent.com/52306865/178889282-a82a94df-1e37-4489-871d-8664ceb2286f.png)
weight的shape不对

**Comment by zjd1988** [comment]
> 作者你好，通过你提供的脚本把onnx模型固定后，通过onnx2ncnn工具转换成了ncnn模型，但是结果如图： ![image](https://user-images.githubusercontent.com/52306865/178889282-a82a94df-1e37-4489-871d-8664ceb2286f.png) weight的shape不对

我本地测试下吧，onnx模型用netron打开是ok的

**Comment by j201111100523** [comment]
感谢作者，onnx模型shape是ok的，但是转换成ncnn就变成我刚刚的截图




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月14日(星期四) 中午11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjd1988/seetaface6_onnx_model] 能帮我把pose_estimation.onnx转成ncnn模型吗？ (Issue #5)





  
作者你好，通过你提供的脚本把onnx模型固定后，通过onnx2ncnn工具转换成了ncnn模型，但是结果如图：  weight的shape不对
  
我本地测试下吧，onnx模型用netron打开是ok的

**Comment by zjd1988** [comment]
@j201111100523 我本地测试ncnn转换跟你遇到的问题一样，感觉像是ncnn的bug，我后边会进行定位。
