### ISSUE TITLE
关于活体检测模型的问题

### ISSUE THREAD

**Issue by cswxaa** [zjd1988/seetaface6_onnx_model#6]
您好，请问您了解关于活体检测模型fas_first.csta与fas_second.csta的模型原理嘛，官方上只给出根据成像细节区分一次成像与二次成像，但并未说根据那种算法判断的，如果您有了解可以讲解下嘛，感谢！

**Comment by zjd1988** [comment]
@cswxaa 抱歉啊，具体模型使用算法没有研究过。

**Comment by cswxaa** [comment]
好的，谢谢！
