### ISSUE TITLE
face_landmarker_pts81.csta 这个81点的文件在可以分享一下嘛？

### ISSUE THREAD

**Issue by zhu260824** [zjd1988/seetaface6_onnx_model#7]
face_landmarker_pts81.csta 这个模型文件可以分享一下不？找了很多地方，没找打这个模型文件。谢啦！

**Comment by zjd1988** [comment]
@zhu260824 你好，这个模型我当时也没有转成onnx，要是不着急的话，我后边找时间可以转一下，其实原理就是根据seetaface的源码对网络进行重建成onnx

**Comment by zhu260824** [comment]
您好，打扰了，我是拿来在seetaface6中使用的，官方库里面只有68点的模型。我想试下81点的模型，会不会提升一下识别精度。

**Comment by zjd1988** [comment]
@zhu260824 官方库里如果没有81点的模型，我就没办法了，不过你可以找个开源的81点的人脸关键点模型，不一定非得用seetaface，seetaface没法对模型做量化加速，github上应该挺多开源81点模型的，你可搜一下

**Comment by zhu260824** [comment]
OK,谢啦
